#!/bin/bash

~/ErrorCorrectReads.pl \
MAX_MEMORY_GB= 30 THREADS= 8 PHRED_ENCODING= 33 PAIRED_READS_A_IN= \
PAIRED_READS_B_IN=  UNPAIRED_READS_IN= sim.fastq \
FE_MAX_KMER_FREQ_TO_MARK= 0 EC_K= 24 HAPLOIDIFY= True FILL_FRAGMENTS= \
False FF_K=28 FE_USE_KMER_SPECTRUM=TRUE READS_OUT=corr